language: scala
sbt_args: -J-Dproject.version=travis-SNAPSHOT
scala:
  - 2.11.7
jdk:
  - openjdk7
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
before_script:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/4527
  - curl --create-dirs -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
